export const GAME = {
  NAMESPACE: 'game',
  ACTIONS: {
    CONNECT_REQUEST: 'CONNECT_REQUEST',
    PLAY_REQUEST: 'PLAY_REQUEST',
    CHECK_STATUS_REQUEST: 'CHECK_STATUS_REQUEST',
    CHECK_LAST_STATUS_REQUEST: 'CHECK_LAST_STATUS_REQUEST',
  },
  MUTATIONS: {
    CONNECT_RESPONSE: 'CONNECT_RESPONSE',
    PLAY_RESPONSE: 'PLAY_RESPONSE',
    CHECK_STATUS_RESPONSE: 'CHECK_STATUS_RESPONSE',
    CHECK_LAST_STATUS_RESPONSE: 'CHECK_LAST_STATUS_RESPONSE',
    RESET: 'RESET',
  },
}
